# Generated by Django 5.2.10 on 2026-02-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='confirm_password',
        ),
    ]
