# Generated by Django 5.2.10 on 2026-02-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_confirm_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts',
            new_name='Account',
        ),
    ]
