# Generated by Django 5.2.10 on 2026-02-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
    ]
