# Generated by Django 5.2.10 on 2026-02-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
