# Generated by Django 5.2.10 on 2026-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_institution_admin',
            field=models.BooleanField(default=False),
        ),
    ]
