# Generated by Django 5.2.10 on 2026-02-14 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 14, 4, 35, 43, 5721, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
