# Generated by Django 5.2.10 on 2026-02-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='join_password',
            field=models.CharField(default='default123', max_length=255),
            preserve_default=False,
        ),
    ]
